global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cloudpulse-data-generator'
    static_configs:
      - targets: ['data-generator:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'aws-cloudwatch'
    ec2_sd_configs:
      - region: us-east-1
        port: 9100
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Project]
        target_label: project
      - source_labels: [__meta_ec2_tag_Environment]
        target_label: environment
